services:
  - type: web
    name: quiz-app
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/quiz-application-1.0.0.jar
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_pgjen2uM7SWJ@ep-delicate-dream-a1jgbc9s-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ORIGINS
        sync: false
    healthCheckPath: /actuator/health
